version: "3"
services:
  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx/conf.d
    ports:
      - ${APP_API_PORT}:80
    depends_on:
      - api
    restart: unless-stopped
  api:
    image: ghcr.io/gobiz-vinasat/image-php-fpm:7.4.1
    volumes:
      - ${APP_BACKEND_SOURCE}:/var/www/html
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: unless-stopped
volumes:
  mysql:
  logs:
